name: 'Generate Changelog'
branding:
  icon: 'tag'
  color: 'purple'
description: 'Create a changelog for every tag you push'
inputs:
  tag:
    description: Specific tag to generate changelog against
    required: false
  exclude:
    description: Regex to exclude commits based on their title (don't include the initial and final `/`)
    required: false
    default: ''
  template:
    description: Markdown template to be included in release notes
    required: false
    default: |
      {commits}

      {range}
  commit-template:
    description: Markdown template for each commit entry in release notes
    required: false
    default: '- {hash} {title}'
  date-format:
    description: Format of git date included in commit-template
    required: false
    default: 'short'
  sort:
    description: Specify if you want get changelog in reverse order
    required: false
    default: 'desc'
outputs:
  changelog:
    description: "Contents of generated change log."
runs:
  using: 'node12'
  main: 'distribution/index.js'
