on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: vedhavyas/generate-changelog
        id: changelog-generator
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog-generator.outputs.changelog }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
